var searchData=
[
  ['q_5fdecl_5fenumerator_5fdeprecated_5fx_461',['Q_DECL_ENUMERATOR_DEPRECATED_X',['../classQXmppStanza_1_1Error.html#abcf1cbbe7b15ec82f3ac34723b604852afe6f471a56ed0a0c6116608a393adb36',1,'QXmppStanza::Error']]],
  ['queryid_462',['queryId',['../classQXmppMamQueryIq.html#a897a7a1aa8464c2737e349b0bfdd887e',1,'QXmppMamQueryIq']]],
  ['queryjid_463',['queryJid',['../classQXmppPubSubIq.html#af5a249b8391a6a020d5b0ec1447eb748',1,'QXmppPubSubIq']]],
  ['querynode_464',['queryNode',['../classQXmppPubSubIq.html#a606c69164283d376a9be351af1325e0f',1,'QXmppPubSubIq']]],
  ['querytype_465',['QueryType',['../classQXmppPubSubIq.html#aeadecfdbdb64593cc7a27cbe9def8359',1,'QXmppPubSubIq::QueryType()'],['../classQXmppPubSubIq.html#abb7e9f9b5953bd68c4eba46e8c2819e4',1,'QXmppPubSubIq::queryType() const']]],
  ['queuedata_466',['queueData',['../classQXmppOutgoingServer.html#aeaab8b4ce42db69ab9cea8ace67a1265',1,'QXmppOutgoingServer']]],
  ['qxmpparchivechat_467',['QXmppArchiveChat',['../classQXmppArchiveChat.html',1,'']]],
  ['qxmpparchivechatiq_468',['QXmppArchiveChatIq',['../classQXmppArchiveChatIq.html',1,'']]],
  ['qxmpparchivelistiq_469',['QXmppArchiveListIq',['../classQXmppArchiveListIq.html',1,'QXmppArchiveListIq'],['../classQXmppArchiveListIq.html#aa940621c68b3d637099e40916bdf5a37',1,'QXmppArchiveListIq::QXmppArchiveListIq()']]],
  ['qxmpparchivemanager_470',['QXmppArchiveManager',['../classQXmppArchiveManager.html',1,'']]],
  ['qxmpparchivemessage_471',['QXmppArchiveMessage',['../classQXmppArchiveMessage.html',1,'']]],
  ['qxmpparchiveprefiq_472',['QXmppArchivePrefIq',['../classQXmppArchivePrefIq.html',1,'']]],
  ['qxmpparchiveremoveiq_473',['QXmppArchiveRemoveIq',['../classQXmppArchiveRemoveIq.html',1,'']]],
  ['qxmpparchiveretrieveiq_474',['QXmppArchiveRetrieveIq',['../classQXmppArchiveRetrieveIq.html',1,'']]],
  ['qxmppattentionmanager_475',['QXmppAttentionManager',['../classQXmppAttentionManager.html',1,'QXmppAttentionManager'],['../classQXmppAttentionManager.html#a8201f5b807074563108c55ae7c10c23b',1,'QXmppAttentionManager::QXmppAttentionManager()']]],
  ['qxmppbindiq_476',['QXmppBindIq',['../classQXmppBindIq.html',1,'']]],
  ['qxmppbitsofbinarycontentid_477',['QXmppBitsOfBinaryContentId',['../classQXmppBitsOfBinaryContentId.html',1,'QXmppBitsOfBinaryContentId'],['../classQXmppBitsOfBinaryContentId.html#ad56eae2542bcc731bce26e41a172f3dc',1,'QXmppBitsOfBinaryContentId::QXmppBitsOfBinaryContentId()']]],
  ['qxmppbitsofbinarydata_478',['QXmppBitsOfBinaryData',['../classQXmppBitsOfBinaryData.html',1,'']]],
  ['qxmppbitsofbinarydatalist_479',['QXmppBitsOfBinaryDataList',['../classQXmppBitsOfBinaryDataList.html',1,'']]],
  ['qxmppbitsofbinaryiq_480',['QXmppBitsOfBinaryIq',['../classQXmppBitsOfBinaryIq.html',1,'']]],
  ['qxmppbookmarkconference_481',['QXmppBookmarkConference',['../classQXmppBookmarkConference.html',1,'QXmppBookmarkConference'],['../classQXmppBookmarkConference.html#a01e949da407d33e9d53b92b7ebe81c68',1,'QXmppBookmarkConference::QXmppBookmarkConference()']]],
  ['qxmppbookmarkmanager_482',['QXmppBookmarkManager',['../classQXmppBookmarkManager.html',1,'QXmppBookmarkManager'],['../classQXmppBookmarkManager.html#af8d7ef4d015752c8b33ac81fd030f165',1,'QXmppBookmarkManager::QXmppBookmarkManager()']]],
  ['qxmppbookmarkset_483',['QXmppBookmarkSet',['../classQXmppBookmarkSet.html',1,'']]],
  ['qxmppbookmarkurl_484',['QXmppBookmarkUrl',['../classQXmppBookmarkUrl.html',1,'']]],
  ['qxmppbytestreamiq_485',['QXmppByteStreamIq',['../classQXmppByteStreamIq.html',1,'']]],
  ['qxmppcall_486',['QXmppCall',['../classQXmppCall.html',1,'']]],
  ['qxmppcallmanager_487',['QXmppCallManager',['../classQXmppCallManager.html',1,'QXmppCallManager'],['../classQXmppCallManager.html#a560d15be90eda576c32fc7765c4495e4',1,'QXmppCallManager::QXmppCallManager()']]],
  ['qxmppcallstream_488',['QXmppCallStream',['../classQXmppCallStream.html',1,'']]],
  ['qxmppcarbonmanager_489',['QXmppCarbonManager',['../classQXmppCarbonManager.html',1,'']]],
  ['qxmppclient_490',['QXmppClient',['../classQXmppClient.html',1,'QXmppClient'],['../classQXmppClient.html#a043546d276debb522e60f0b77e137ce6',1,'QXmppClient::QXmppClient()']]],
  ['qxmppclientextension_491',['QXmppClientExtension',['../classQXmppClientExtension.html',1,'QXmppClientExtension'],['../classQXmppClientExtension.html#aec299452688f50431f1028668186e3ec',1,'QXmppClientExtension::QXmppClientExtension()']]],
  ['qxmppconfiguration_492',['QXmppConfiguration',['../classQXmppConfiguration.html',1,'QXmppConfiguration'],['../classQXmppConfiguration.html#acd68380ad2353139a8c29087c40e4dcc',1,'QXmppConfiguration::QXmppConfiguration()'],['../classQXmppConfiguration.html#ac91c247c5ee60472abb5393f9e32d0f2',1,'QXmppConfiguration::QXmppConfiguration(const QXmppConfiguration &amp;other)']]],
  ['qxmppdataform_493',['QXmppDataForm',['../classQXmppDataForm.html',1,'QXmppDataForm'],['../classQXmppDataForm.html#a058f203f616dbffbd32043f509a9ff65',1,'QXmppDataForm::QXmppDataForm(QXmppDataForm::Type type=QXmppDataForm::None)'],['../classQXmppDataForm.html#a976fd7811d7f937fd2f9a7d313eb7ca8',1,'QXmppDataForm::QXmppDataForm(const QXmppDataForm &amp;other)']]],
  ['qxmppdialback_494',['QXmppDialback',['../classQXmppDialback.html',1,'QXmppDialback'],['../classQXmppDialback.html#a1aa371e5859efa4eb5a5a733f609db3e',1,'QXmppDialback::QXmppDialback()']]],
  ['qxmppdiscoveryiq_495',['QXmppDiscoveryIq',['../classQXmppDiscoveryIq.html',1,'']]],
  ['qxmppdiscoverymanager_496',['QXmppDiscoveryManager',['../classQXmppDiscoveryManager.html',1,'']]],
  ['qxmppelement_497',['QXmppElement',['../classQXmppElement.html',1,'']]],
  ['qxmppentitytimeiq_498',['QXmppEntityTimeIq',['../classQXmppEntityTimeIq.html',1,'']]],
  ['qxmppentitytimemanager_499',['QXmppEntityTimeManager',['../classQXmppEntityTimeManager.html',1,'']]],
  ['qxmppextendedaddress_500',['QXmppExtendedAddress',['../classQXmppExtendedAddress.html',1,'QXmppExtendedAddress'],['../classQXmppExtendedAddress.html#a977ce245d062f5cb8398b02ecff76163',1,'QXmppExtendedAddress::QXmppExtendedAddress()'],['../classQXmppExtendedAddress.html#a2a88bb47091f713d6b8176ab2ee1101f',1,'QXmppExtendedAddress::QXmppExtendedAddress(const QXmppExtendedAddress &amp;)']]],
  ['qxmpphttpuploadrequestiq_501',['QXmppHttpUploadRequestIq',['../classQXmppHttpUploadRequestIq.html',1,'']]],
  ['qxmpphttpuploadslotiq_502',['QXmppHttpUploadSlotIq',['../classQXmppHttpUploadSlotIq.html',1,'']]],
  ['qxmppibbcloseiq_503',['QXmppIbbCloseIq',['../classQXmppIbbCloseIq.html',1,'']]],
  ['qxmppibbdataiq_504',['QXmppIbbDataIq',['../classQXmppIbbDataIq.html',1,'']]],
  ['qxmppibbopeniq_505',['QXmppIbbOpenIq',['../classQXmppIbbOpenIq.html',1,'']]],
  ['qxmppicecomponent_506',['QXmppIceComponent',['../classQXmppIceComponent.html',1,'']]],
  ['qxmppiceconnection_507',['QXmppIceConnection',['../classQXmppIceConnection.html',1,'QXmppIceConnection'],['../classQXmppIceConnection.html#a2dd13dd42ab4a2461ca0d261cd481c03',1,'QXmppIceConnection::QXmppIceConnection()']]],
  ['qxmppincomingclient_508',['QXmppIncomingClient',['../classQXmppIncomingClient.html',1,'QXmppIncomingClient'],['../classQXmppIncomingClient.html#a835a786261612a98317252c6ce5e2bba',1,'QXmppIncomingClient::QXmppIncomingClient()']]],
  ['qxmppincomingserver_509',['QXmppIncomingServer',['../classQXmppIncomingServer.html',1,'QXmppIncomingServer'],['../classQXmppIncomingServer.html#a35f13c6597f2c46fe220e7f9f612832c',1,'QXmppIncomingServer::QXmppIncomingServer()']]],
  ['qxmppinvokable_510',['QXmppInvokable',['../classQXmppInvokable.html',1,'QXmppInvokable'],['../classQXmppInvokable.html#a5659a46cca37bfd0641eb43abda86c19',1,'QXmppInvokable::QXmppInvokable()']]],
  ['qxmppiq_511',['QXmppIq',['../classQXmppIq.html',1,'QXmppIq'],['../classQXmppIq.html#a16db985e7cbf842dbca1cb94ec57c64f',1,'QXmppIq::QXmppIq(QXmppIq::Type type=QXmppIq::Get)'],['../classQXmppIq.html#a64c242ce6d42d7013d53120c58be5da2',1,'QXmppIq::QXmppIq(const QXmppIq &amp;other)']]],
  ['qxmppjinglecandidate_512',['QXmppJingleCandidate',['../classQXmppJingleCandidate.html',1,'QXmppJingleCandidate'],['../classQXmppJingleCandidate.html#a89e3d8d6e31b950036689c57b185f394',1,'QXmppJingleCandidate::QXmppJingleCandidate()'],['../classQXmppJingleCandidate.html#a4332c0ec01cd2d46e27dac58ac4f1bbb',1,'QXmppJingleCandidate::QXmppJingleCandidate(const QXmppJingleCandidate &amp;other)']]],
  ['qxmppjingleiq_513',['QXmppJingleIq',['../classQXmppJingleIq.html',1,'QXmppJingleIq'],['../classQXmppJingleIq.html#aeb7657fe2e9f6d5a9da2beef434625ff',1,'QXmppJingleIq::QXmppJingleIq()'],['../classQXmppJingleIq.html#aed3e111b999ea8bc23d5d45c1af5a402',1,'QXmppJingleIq::QXmppJingleIq(const QXmppJingleIq &amp;other)']]],
  ['qxmppjinglepayloadtype_514',['QXmppJinglePayloadType',['../classQXmppJinglePayloadType.html',1,'QXmppJinglePayloadType'],['../classQXmppJinglePayloadType.html#adf7649529f4f0cff32cf1a15c3618993',1,'QXmppJinglePayloadType::QXmppJinglePayloadType()']]],
  ['qxmpploggable_515',['QXmppLoggable',['../classQXmppLoggable.html',1,'QXmppLoggable'],['../classQXmppLoggable.html#ab900d699019726ee43285dc7072a600b',1,'QXmppLoggable::QXmppLoggable()']]],
  ['qxmpplogger_516',['QXmppLogger',['../classQXmppLogger.html',1,'QXmppLogger'],['../classQXmppLogger.html#af21d8365b667a12e29dc689bdc28150e',1,'QXmppLogger::QXmppLogger()']]],
  ['qxmppmammanager_517',['QXmppMamManager',['../classQXmppMamManager.html',1,'']]],
  ['qxmppmamqueryiq_518',['QXmppMamQueryIq',['../classQXmppMamQueryIq.html',1,'']]],
  ['qxmppmamresultiq_519',['QXmppMamResultIq',['../classQXmppMamResultIq.html',1,'']]],
  ['qxmppmessage_520',['QXmppMessage',['../classQXmppMessage.html',1,'QXmppMessage'],['../classQXmppMessage.html#a557b618ed65c4b355cac1385ac21cd3a',1,'QXmppMessage::QXmppMessage(const QString &amp;from=QString(), const QString &amp;to=QString(), const QString &amp;body=QString(), const QString &amp;thread=QString())'],['../classQXmppMessage.html#af73b605ad48ee6ecc111975f774c6edd',1,'QXmppMessage::QXmppMessage(const QXmppMessage &amp;other)']]],
  ['qxmppmessagereceiptmanager_521',['QXmppMessageReceiptManager',['../classQXmppMessageReceiptManager.html',1,'QXmppMessageReceiptManager'],['../classQXmppMessageReceiptManager.html#abd24b74a2784930429f1e9df1d7704fa',1,'QXmppMessageReceiptManager::QXmppMessageReceiptManager()']]],
  ['qxmppmixinfoitem_522',['QXmppMixInfoItem',['../classQXmppMixInfoItem.html',1,'']]],
  ['qxmppmixinvitation_523',['QXmppMixInvitation',['../classQXmppMixInvitation.html',1,'QXmppMixInvitation'],['../classQXmppMixInvitation.html#aa98deedb9a14240f42fa55c40d3890e5',1,'QXmppMixInvitation::QXmppMixInvitation()'],['../classQXmppMixInvitation.html#a61d9ddaa5c83bb3695dfecd87f85fc38',1,'QXmppMixInvitation::QXmppMixInvitation(const QXmppMixInvitation &amp;other)']]],
  ['qxmppmixiq_524',['QXmppMixIq',['../classQXmppMixIq.html',1,'']]],
  ['qxmppmixparticipantitem_525',['QXmppMixParticipantItem',['../classQXmppMixParticipantItem.html',1,'']]],
  ['qxmppmucadminiq_526',['QXmppMucAdminIq',['../classQXmppMucAdminIq.html',1,'']]],
  ['qxmppmucitem_527',['QXmppMucItem',['../classQXmppMucItem.html',1,'']]],
  ['qxmppmucmanager_528',['QXmppMucManager',['../classQXmppMucManager.html',1,'QXmppMucManager'],['../classQXmppMucManager.html#a0eb8a3dbacfa9983e2ac72cd6a7629a3',1,'QXmppMucManager::QXmppMucManager()']]],
  ['qxmppmucowneriq_529',['QXmppMucOwnerIq',['../classQXmppMucOwnerIq.html',1,'']]],
  ['qxmppmucroom_530',['QXmppMucRoom',['../classQXmppMucRoom.html',1,'']]],
  ['qxmppnonsaslauthiq_531',['QXmppNonSASLAuthIq',['../classQXmppNonSASLAuthIq.html',1,'']]],
  ['qxmppoutgoingclient_532',['QXmppOutgoingClient',['../classQXmppOutgoingClient.html',1,'QXmppOutgoingClient'],['../classQXmppOutgoingClient.html#a6713a94557a69df0051039b6f9a9cf3c',1,'QXmppOutgoingClient::QXmppOutgoingClient()']]],
  ['qxmppoutgoingserver_533',['QXmppOutgoingServer',['../classQXmppOutgoingServer.html',1,'QXmppOutgoingServer'],['../classQXmppOutgoingServer.html#a10e2b65e7bc9957db290b0a6de931bed',1,'QXmppOutgoingServer::QXmppOutgoingServer()']]],
  ['qxmpppasswordchecker_534',['QXmppPasswordChecker',['../classQXmppPasswordChecker.html',1,'']]],
  ['qxmpppasswordreply_535',['QXmppPasswordReply',['../classQXmppPasswordReply.html',1,'QXmppPasswordReply'],['../classQXmppPasswordReply.html#ac2451604e8bff3ef201c81e6af8c403e',1,'QXmppPasswordReply::QXmppPasswordReply()']]],
  ['qxmpppasswordrequest_536',['QXmppPasswordRequest',['../classQXmppPasswordRequest.html',1,'']]],
  ['qxmpppingiq_537',['QXmppPingIq',['../classQXmppPingIq.html',1,'']]],
  ['qxmpppresence_538',['QXmppPresence',['../classQXmppPresence.html',1,'QXmppPresence'],['../classQXmppPresence.html#ab3facb1c108a346c1866f11133592601',1,'QXmppPresence::QXmppPresence(QXmppPresence::Type type=QXmppPresence::Available)'],['../classQXmppPresence.html#a74ef4824a0c7c70c095c9e783a3b55b4',1,'QXmppPresence::QXmppPresence(const QXmppPresence &amp;other)']]],
  ['qxmpppubsubiq_539',['QXmppPubSubIq',['../classQXmppPubSubIq.html',1,'']]],
  ['qxmpppubsubitem_540',['QXmppPubSubItem',['../classQXmppPubSubItem.html',1,'']]],
  ['qxmpppushenableiq_541',['QXmppPushEnableIq',['../classQXmppPushEnableIq.html',1,'']]],
  ['qxmppregisteriq_542',['QXmppRegisterIq',['../classQXmppRegisterIq.html',1,'']]],
  ['qxmppregistrationmanager_543',['QXmppRegistrationManager',['../classQXmppRegistrationManager.html',1,'QXmppRegistrationManager'],['../classQXmppRegistrationManager.html#ab05276145d09d578981bd2994fbe1c40',1,'QXmppRegistrationManager::QXmppRegistrationManager()']]],
  ['qxmppresultsetquery_544',['QXmppResultSetQuery',['../classQXmppResultSetQuery.html',1,'']]],
  ['qxmppresultsetreply_545',['QXmppResultSetReply',['../classQXmppResultSetReply.html',1,'']]],
  ['qxmpprosteriq_546',['QXmppRosterIq',['../classQXmppRosterIq.html',1,'']]],
  ['qxmpprostermanager_547',['QXmppRosterManager',['../classQXmppRosterManager.html',1,'QXmppRosterManager'],['../classQXmppRosterManager.html#aa96bd124e15813b402bc1de93f9e4f7b',1,'QXmppRosterManager::QXmppRosterManager()']]],
  ['qxmpprpcinvokeiq_548',['QXmppRpcInvokeIq',['../classQXmppRpcInvokeIq.html',1,'']]],
  ['qxmpprpcmanager_549',['QXmppRpcManager',['../classQXmppRpcManager.html',1,'QXmppRpcManager'],['../classQXmppRpcManager.html#a8fece0110e91b17f2868575303d7c90f',1,'QXmppRpcManager::QXmppRpcManager()']]],
  ['qxmpprpcresponseiq_550',['QXmppRpcResponseIq',['../classQXmppRpcResponseIq.html',1,'']]],
  ['qxmppserver_551',['QXmppServer',['../classQXmppServer.html',1,'QXmppServer'],['../classQXmppServer.html#a70c0a7b8c326156554a53a2c7c30705f',1,'QXmppServer::QXmppServer()']]],
  ['qxmppserverextension_552',['QXmppServerExtension',['../classQXmppServerExtension.html',1,'']]],
  ['qxmppserverplugin_553',['QXmppServerPlugin',['../classQXmppServerPlugin.html',1,'']]],
  ['qxmppsessioniq_554',['QXmppSessionIq',['../classQXmppSessionIq.html',1,'']]],
  ['qxmppsslserver_555',['QXmppSslServer',['../classQXmppSslServer.html',1,'QXmppSslServer'],['../classQXmppSslServer.html#aebbc08448807f39b706271107734156a',1,'QXmppSslServer::QXmppSslServer()']]],
  ['qxmppstanza_556',['QXmppStanza',['../classQXmppStanza.html',1,'QXmppStanza'],['../classQXmppStanza.html#aeda5073d2af6c52e78f127bca4306ace',1,'QXmppStanza::QXmppStanza(const QString &amp;from=QString(), const QString &amp;to=QString())'],['../classQXmppStanza.html#af8e4636d056c754347635ba26cd8d60c',1,'QXmppStanza::QXmppStanza(const QXmppStanza &amp;other)']]],
  ['qxmppstarttlspacket_557',['QXmppStartTlsPacket',['../classQXmppStartTlsPacket.html',1,'QXmppStartTlsPacket'],['../classQXmppStartTlsPacket.html#a62c42a11cf2fad3061cf0ec2bb1a1ff8',1,'QXmppStartTlsPacket::QXmppStartTlsPacket()']]],
  ['qxmppstream_558',['QXmppStream',['../classQXmppStream.html',1,'QXmppStream'],['../classQXmppStream.html#a70a8f8a0734c3a681fb0079890d99786',1,'QXmppStream::QXmppStream()']]],
  ['qxmppstreamfeatures_559',['QXmppStreamFeatures',['../classQXmppStreamFeatures.html',1,'']]],
  ['qxmpptransferjob_560',['QXmppTransferJob',['../classQXmppTransferJob.html',1,'']]],
  ['qxmpptransfermanager_561',['QXmppTransferManager',['../classQXmppTransferManager.html',1,'QXmppTransferManager'],['../classQXmppTransferManager.html#aa88b03ffc2b9039a50bae7e79e759ed7',1,'QXmppTransferManager::QXmppTransferManager()']]],
  ['qxmppuploadrequestmanager_562',['QXmppUploadRequestManager',['../classQXmppUploadRequestManager.html',1,'']]],
  ['qxmppuploadservice_563',['QXmppUploadService',['../classQXmppUploadService.html',1,'QXmppUploadService'],['../classQXmppUploadService.html#a3e1e34add53e8db7ec0f1c41863033d8',1,'QXmppUploadService::QXmppUploadService()']]],
  ['qxmpputils_564',['QXmppUtils',['../classQXmppUtils.html',1,'']]],
  ['qxmppvcardaddress_565',['QXmppVCardAddress',['../classQXmppVCardAddress.html',1,'QXmppVCardAddress'],['../classQXmppVCardAddress.html#ab31c2eab8fb090d6716515cfe0fad36b',1,'QXmppVCardAddress::QXmppVCardAddress()'],['../classQXmppVCardAddress.html#a2093d0ed8737c0f04ffa543c3943f0a9',1,'QXmppVCardAddress::QXmppVCardAddress(const QXmppVCardAddress &amp;other)']]],
  ['qxmppvcardemail_566',['QXmppVCardEmail',['../classQXmppVCardEmail.html',1,'QXmppVCardEmail'],['../classQXmppVCardEmail.html#ac2d3a7f08975a9d6a395c8ed60d1a4ef',1,'QXmppVCardEmail::QXmppVCardEmail()'],['../classQXmppVCardEmail.html#a769b18f711a4bca0a6de8f7707e89a0b',1,'QXmppVCardEmail::QXmppVCardEmail(const QXmppVCardEmail &amp;other)']]],
  ['qxmppvcardiq_567',['QXmppVCardIq',['../classQXmppVCardIq.html',1,'QXmppVCardIq'],['../classQXmppVCardIq.html#a661553fef688e1533f502ea233a3cd80',1,'QXmppVCardIq::QXmppVCardIq(const QString &amp;bareJid=QString())'],['../classQXmppVCardIq.html#a7e09646833b005171d2f3564cb446e91',1,'QXmppVCardIq::QXmppVCardIq(const QXmppVCardIq &amp;other)']]],
  ['qxmppvcardmanager_568',['QXmppVCardManager',['../classQXmppVCardManager.html',1,'']]],
  ['qxmppvcardorganization_569',['QXmppVCardOrganization',['../classQXmppVCardOrganization.html',1,'QXmppVCardOrganization'],['../classQXmppVCardOrganization.html#aec7c608b926fe03e172d487e8914eb8e',1,'QXmppVCardOrganization::QXmppVCardOrganization()'],['../classQXmppVCardOrganization.html#ae90e5c2e9948b681145123b4f77c8ec7',1,'QXmppVCardOrganization::QXmppVCardOrganization(const QXmppVCardOrganization &amp;other)']]],
  ['qxmppvcardphone_570',['QXmppVCardPhone',['../classQXmppVCardPhone.html',1,'QXmppVCardPhone'],['../classQXmppVCardPhone.html#ab8227e376f5aba012a8e05d6f09c7c6a',1,'QXmppVCardPhone::QXmppVCardPhone()'],['../classQXmppVCardPhone.html#acd06e5045a4f27ce29a0bf34b6d4653c',1,'QXmppVCardPhone::QXmppVCardPhone(const QXmppVCardPhone &amp;other)']]],
  ['qxmppversioniq_571',['QXmppVersionIq',['../classQXmppVersionIq.html',1,'']]],
  ['qxmppversionmanager_572',['QXmppVersionManager',['../classQXmppVersionManager.html',1,'']]]
];
